version: 0.0
os: linux
files:
  - source: /papplan
    destination: /home/ubuntu/app/papplan
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: papplan/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: papplan/start.sh
      timeout: 60
      runas: ubuntu
