spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.31.47.144:3307/papplan
    # url: jdbc:mariadb://54.150.211.146:3306/papplan
    username: root
    # password: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false

# Hibernate SQL ?? ?? ??
logging:
  level:
    org:
      hibernate:
        SQL: debug

