spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/papplan
    username: root
    password: maria
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true

# Hibernate SQL 디버깅 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug

devtools:
  liverload:
    enable: true
