spring:
  sql:
    init:
      platform: mariadb
      encoding: UTF-8
      mode: always
      schema-locations: classpath:init-db-script/a_create_table.sql
      data-locations: classpath:init-db-script/b_insert_table.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MariaDB
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true

# Hibernate SQL ?? ?? ??
logging:
  level:
    org:
      hibernate:
        SQL: debug

devtools:
  LiveReload:
    enable: true